apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    name: helloworld-service

spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 3000