apiVersion: v1
kind: ReplicationController
metdata:
  name:  myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: fromt-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
